In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML
from collections import defaultdict
from sklearn.model_selection import KFold
import time

pd.set_option('display.max_columns', 50)

from evaluation_and_testing.testing import evaluate_train_test_split_explicit
from evaluation_and_testing.testing import evaluate_leave_one_out_explicit
from evaluation_and_testing.testing import evaluate_train_test_split_implicit
from evaluation_and_testing.testing import evaluate_leave_one_out_implicit

from recommenders.recommender import Recommender

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Load the data

In [3]:
ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv")).rename(columns={'userId': 'user_id', 'movieId': 'item_id'})
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv")).rename(columns={'movieId': 'item_id'})
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='item_id')

display(ml_movies_df.head(10))

# Filter the data to reduce the number of movies
seed = 6789
rng = np.random.RandomState(seed=seed)
left_ids = rng.choice(ml_movies_df['item_id'], size=1000, replace=False)

ml_ratings_df = ml_ratings_df.loc[ml_ratings_df['item_id'].isin(left_ids)]
ml_movies_df = ml_movies_df.loc[ml_movies_df['item_id'].isin(left_ids)]
ml_df = ml_df.loc[ml_df['item_id'].isin(left_ids)]

print("Number of left interactions: {}".format(len(ml_ratings_df)))

,item_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

Number of left interactions: 9692

# Baseline recommenders

**Task 1.** Implement the MostPopularRecommender (check the slides for class 1), evaluate it with leave-one-out procedure for implicit feedback, print HR@1, HR@3, HR@5, HR@10, NDCG@1, NDCG@3, NDCG@5, NDCG@10.

In [7]:
class MostPopularRecommender(Recommender):
    """
    Base recommender class.
    """
    
    def __init__(self):
        """
        Initialize base recommender params and variables.
        """
        self.most_popular_item = None
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        # Write your code here
        items_pupularity = interactions_df.loc[:, ['item_id', 'user_id']].groupby(by='item_id', as_index=False).count()
       # items_pupularity = items_pupularity.rename(columns={'user_id': 'popularity'})
        self.most_popular_item = items_pupularity.sort_values('user_id', ascending=False).head(1)['item_id'].values[0]
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        for ix, user in users_df.iterrows():
            user_recommendations = pd.DataFrame({'user_id': [user['user_id']],
                                                 'item_id': [self.most_popular_item],
                                                 'score': [1.0]})

            recommendations = pd.concat([recommendations, user_recommendations])

        return recommendations


# class MostPopularRecommender(Recommender):
    
#     def __init__(self):
#         self.most_popular_items = None
    
#     def fit(self, interactions_df, users_df, items_df):
#         offers_count = interactions_df.loc[:, ['item_id', 'user_id']].groupby(by='item_id', as_index=False).count()
#         self.most_popular_items = offers_count.sort_values('user_id', ascending=False)
    
#     def recommend(self, users_df, items_df, n_recommendations=1):
       
#         recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
#         for ix, user in users_df.iterrows():
#             user_recommendations = pd.DataFrame({'user_id': user['user_id'],
#                                                  'item_id': self.most_popular_items.iloc[:n_recommendations]['item_id'],
#                                                  'score': [1 / (i + 1) for i in range(0, n_recommendations)]})

#             recommendations = pd.concat([recommendations, user_recommendations])

#         return recommendations 

# Quick test of the recommender

most_popular_recommender = MostPopularRecommender()
most_popular_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = most_popular_recommender.recommend(pd.DataFrame([[1], [2], [6]], columns=['user_id']), ml_movies_df, 10)

display(recommendations)
display(ml_movies_df)
recommendations = pd.merge(recommendations, ml_movies_df, on='item_id', how='left')
print("Recommendations")
display(HTML(recommendations.to_html()))

most_popular_recommender = MostPopularRecommender()

most_popular_results = [['MostPopularRecommender'] + list(evaluate_leave_one_out_implicit(
    most_popular_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id']], ml_movies_df, max_evals=300, seed=6789))]

most_popular_results = pd.DataFrame(
    most_popular_results, 
    columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(HTML(most_popular_results.to_html()))

  user_id item_id  score
0       1      50    1.0
0       2      50    1.0
0       6      50    1.0

,item_id,title,genres
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
46,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
66,74,Bed of Roses (1996),Drama|Romance
70,78,"Crossing Guard, The (1995)",Action|Crime|Drama|Thriller
...,...,...,...
9697,184987,A Wrinkle in Time (2018),Adventure|Children|Fantasy|Sci-Fi
9704,185473,Blockers (2018),Comedy
9721,189381,SuperFly (2018),Action|Crime|Thriller
9725,190207,Tilt (2011),Drama|Romance
9727,190213,John From (2015),Drama

Recommendations

**Task 2.** Implement the HighestRatedRecommender (check the slides for class 1), evaluate it with leave-one-out procedure for implicit feedback, print HR@1, HR@3, HR@5, HR@10, NDCG@1, NDCG@3, NDCG@5, NDCG@10.

In [26]:
# class HighestRatedRecommender(Recommender):
#     """
#     Base recommender class.
#     """
    
#     def __init__(self):
#         """
#         Initialize base recommender params and variables.
#         """
#         self.highest_rated_item = None
    
#     def fit(self, interactions_df, users_df, items_df):
#         """
#         Training of the recommender.
        
#         :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
#             defined by user_id, item_id and features of the interaction.
#         :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
#         :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
#         """
#         # Write your code here
    
#     def recommend(self, users_df, items_df, n_recommendations=1):
#         """
#         Serving of recommendations. Scores items in items_df for each user in users_df and returns 
#         top n_recommendations for each user.
        
#         :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
#         :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
#         :param int n_recommendations: Number of recommendations to be returned for each user.
#         :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
#             for each user.
#         :rtype: pd.DataFrame
#         """
        
#         recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
#         for ix, user in users_df.iterrows():
#             # Write your code here

#             recommendations = pd.concat([recommendations, user_recommendations])

#         return recommendations
    
    
# class HighestRatedRecommender(Recommender):
    
#     def __init__(self):

#         self.highest_rated_item = None
    
#     def fit(self, interactions_df, users_df, items_df):

#         offer_ratings = interactions_df.loc[:, ['item_id', 'rating']].groupby(by='item_id', as_index=False).mean()
        
#         self.highest_rated_item = offer_ratings.sort_values('rating', ascending=False)

    
#     def recommend(self, users_df, items_df, n_recommendations=1):
       
#         recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
#         for ix, user in users_df.iterrows():
#             user_recommendations = pd.DataFrame({'user_id': user['user_id'],
#                                                  'item_id': self.highest_rated_item.iloc[:n_recommendations]['item_id'],
#                                                  'score': self.highest_rated_item.iloc[:n_recommendations]['rating'] / 5 })

#             recommendations = pd.concat([recommendations, user_recommendations])

#         return recommendations
    
class HighestRatedRecommender(Recommender):

    def __init__(self):
        self.highest_rated_items = None

    def fit(self, interactions_df, users_df, items_df):

        offer_ratings = interactions_df.loc[:, ['item_id', 'rating']].groupby(by='item_id', as_index=False).mean()
        offer_counts = interactions_df.loc[:, ['item_id', 'rating']].groupby(by='item_id', as_index=False).count()
        self.highest_rated_items = offer_ratings.loc[offer_counts['rating'] >= 50].sort_values('rating', ascending=False)

    def recommend(self, users_df, items_df, n_recommendations=1):

        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        for ix, user in users_df.iterrows():
            user_recommendations = pd.DataFrame({'user_id': user['user_id'],
                                                 'item_id': self.highest_rated_items.iloc[:n_recommendations]['item_id'],
                                                 'score':  self.highest_rated_items.iloc[:n_recommendations]['rating'] / 5})

            recommendations = pd.concat([recommendations, user_recommendations])

        return recommendations
# Quick test of the recommender

highest_rated_recommender = HighestRatedRecommender()
highest_rated_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = highest_rated_recommender.recommend(pd.DataFrame([[1], [2], [6]], columns=['user_id']), ml_movies_df, 10)

recommendations = pd.merge(recommendations, ml_movies_df, on='item_id')
print("Recommendations")
display(HTML(recommendations.to_html()))

highest_rated_recommender = HighestRatedRecommender()

highest_rated_results = [['HighestRatedRecommender'] + list(evaluate_leave_one_out_implicit(
    highest_rated_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id', 'rating']], ml_movies_df, max_evals=300, seed=6789))]

highest_rated_results = pd.DataFrame(
    highest_rated_results, 
    columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(HTML(highest_rated_results.to_html()))

Recommendations

**Task 3.** Implement the RandomRecommender (check the slides for class 1), evaluate it with leave-one-out procedure for implicit feedback, print HR@1, HR@3, HR@5, HR@10, NDCG@1, NDCG@3, NDCG@5, NDCG@10.

In [27]:
class RandomRecommender(Recommender):
    """
    Base recommender class.
    """
    
    def __init__(self, seed=0):
        """
        Initialize base recommender params and variables.
        
        :param int seed: Seed for the random number generator.
        """
        self.seed = seed
        self.rng = np.random.RandomState(seed=seed)
        self.items = []
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        self.items = items_df['item_id'].unique().tolist()
    
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        # Write your code here
        for ix, user in users_df.iterrows():
            user_recommendations = pd.DataFrame({'user_id': user['user_id'],
                                                 'item_id': self.rng.choice(self.items, n_recommendations, replace=False),
                                                 'score': 1.0})

            recommendations = pd.concat([recommendations, user_recommendations])
            
        recommendations = recommendations.reset_index(drop=True)

        return recommendations

# Quick test of the recommender

random_recommender = RandomRecommender(seed=6789)
random_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = random_recommender.recommend(pd.DataFrame([[1], [2], [6]], columns=['user_id']), ml_movies_df, 10)

recommendations = recommendations.merge(ml_movies_df, on='item_id', how='left')
print("Recommendations")
display(HTML(recommendations.to_html()))

random_recommender = RandomRecommender(seed=seed)

random_results = [['RandomRecommender'] + list(evaluate_leave_one_out_implicit(
    random_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id', 'rating']], ml_movies_df, max_evals=300, seed=seed))]

random_results = pd.DataFrame(
    random_results, 
    columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(HTML(random_results.to_html()))

Recommendations

# Linear Regression Recommender

For every movie we transform its genres into one-hot encoded features and we normalize them, for every user we count percentages for all genres how often do they appear among films watched by the user, we multiply both vectors (for the item and the user) to obtain explanaytory variables, and then we fit a linear regression model to those features and actual ratings.

**Task 4.** Implement the calculate_user_genres method for calculating a DataFrame with one row per user and columns corresponding to genres (e.g. 'user_action', 'user_drama') with values calculated as follows:

- count the number of times a given user watched a given genre,
- apply a natural logarithm to this value plus one,
- normalize those values so that the sum of them over all columns within a row is equal to 1.

Implement the calculate_item_genres method for replacing the 'genres' column with one column per genre (e.g. 'action', 'drama') with values calculated as follows:

- place 1 in every column for which the genre appears in genres,
- normalize those values so that the sum of them over all genre columns within a row is equal to 1.

If item_features is None, then first find all genres and prepare a list of them. If item_features is not None, then create columns baed on this list. Return both the transformed DataFrame and the list of genres. Do not use MultiLabelBinarizer.

Note that in this second method you have to preserve the remaining structure of the DataFrame.

Evaluate the LinearRegressionRecommender with it using leave-one-out procedure for implicit feedback, print HR@1, HR@3, HR@5, HR@10, NDCG@1, NDCG@3, NDCG@5, NDCG@10.

In [28]:
# Prepare data for tests
interactions_df = pd.merge(ml_ratings_df, ml_movies_df, on='item_id')
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace("-", "_", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace(" ", "_", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace("(", "", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace(")", "", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.lower()
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.split("|")

In [35]:
def calculate_user_genres(interactions_df):
    users_df = interactions_df.copy()
    users_df = users_df[['user_id', 'genres']]
    users_df = users_df.explode('genres') # create row for each genre for each user
    users_df['val'] = 1
    users_df = users_df.pivot_table(index='user_id', columns='genres', values='val', aggfunc='count')
    users_df = users_df / users_df.sum(axis=1).values.reshape(-1, 1)
    users_df = users_df.rename_axis(None, axis=1).fillna(0)    # fill NaN values with 0
    users_df = users_df.add_prefix('user_')    # rename columns, 'user_id' is index so we dont have user_user_id name problem
    return users_df

In [36]:
# Test the calculate_user_genres method
display(calculate_user_genres(interactions_df))

,user_action,user_adventure,user_animation,user_children,user_comedy,user_crime,user_documentary,user_drama,user_fantasy,user_film_noir,user_horror,user_imax,user_musical,user_mystery,user_no_genres_listed,user_romance,user_sci_fi,user_thriller,user_war,user_western
user_id,,,,,,,,,,,,,,,,,,,,
1,0.149254,0.119403,0.044776,0.074627,0.119403,0.089552,0.000000,0.059701,0.044776,0.000000,0.000000,0.000000,0.014925,0.014925,0.0,0.074627,0.059701,0.089552,0.029851,0.014925
2,0.125000,0.000000,0.000000,0.000000,0.000000,0.125000,0.000000,0.375000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.062500,0.062500,0.187500,0.000000,0.062500
3,0.285714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.285714,0.142857,0.000000,0.000000
4,0.017857,0.017857,0.035714,0.053571,0.196429,0.089286,0.000000,0.267857,0.035714,0.017857,0.000000,0.017857,0.053571,0.000000,0.0,0.125000,0.000000,0.035714,0.017857,0.017857
5,0.000000,0.000000,0.058824,0.058824,0.058824,0.058824,0.000000,0.176471,0.058824,0.000000,0.000000,0.058824,0.058824,0.058824,0.0,0.176471,0.000000,0.058824,0.058824,0.058824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.048889,0.040000,0.008889,0.022222,0.164444,0.066667,0.004444,0.297778,0.044444,0.004444,0.013333,0.008889,0.004444,0.022222,0.0,0.124444,0.031111,0.066667,0.022222,0.004444
607,0.148936,0.063830,0.000000,0.021277,0.127660,0.085106,0.000000,0.212766,0.021277,0.000000,0.063830,0.000000,0.021277,0.021277,0.0,0.042553,0.085106,0.063830,0.021277,0.000000
608,0.120172,0.055794,0.021459,0.064378,0.184549,0.077253,0.000000,0.107296,0.055794,0.000000,0.051502,0.008584,0.008584,0.017167,0.0,0.042918,0.077253,0.098712,0.008584,0.000000
609,0.200000,0.400000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.200000,0.000000,0.000000,0.000000
610,0.151899,0.063291,0.015823,0.015823,0.107595,0.069620,0.000000,0.110759,0.034810,0.003165,0.110759,0.031646,0.003165,0.034810,0.0,0.022152,0.085443,0.123418,0.009494,0.006329

In [39]:
from sklearn.preprocessing import MultiLabelBinarizer

def calculate_item_genres(item_genres, item_features=None):  
    item_genres = item_genres.copy()
    
    if item_features is None:
        mlb = MultiLabelBinarizer()
        item_genres = item_genres.join(
            pd.DataFrame(mlb.fit_transform(item_genres.pop('genres')),
                         columns=mlb.classes_,
                         index=item_genres.index))

        item_genres[mlb.classes_] = item_genres[mlb.classes_] \
            / item_genres[mlb.classes_].sum(axis=1).values.reshape(-1, 1)
        
        item_features = list(mlb.classes_)
    else:
        item_genres_pivot = item_genres[['item_id', 'genres']].explode('genres')
        item_genres_pivot['val'] = 1
        item_genres_pivot = item_genres_pivot.pivot_table(index='item_id', columns='genres', values='val')
        item_genres_pivot = item_genres_pivot.rename_axis(None, axis=1).fillna(0)
        item_genres_pivot = item_genres_pivot.reindex(item_features, axis=1).fillna(0).reset_index()
        item_genres = item_genres.merge(item_genres_pivot, on='item_id')
        
        item_genres[item_features] = item_genres[item_features] \
            / item_genres[item_features].sum(axis=1).values.reshape(-1, 1)
    
    return item_genres, item_features

In [40]:
# Test the calculate_item_genres method

item_genres, item_features = calculate_item_genres(interactions_df)
display(item_genres)
print(item_features)

item_genres, item_features = calculate_item_genres(interactions_df, ['comedy', 'crime', 'drama', 'horror', 'test_category'])
display(item_genres)
print(item_features)

,user_id,item_id,rating,timestamp,title,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,no_genres_listed,romance,sci_fi,thriller,war,western
0,1,50,5.0,964982931,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.0,0.0
1,5,50,4.0,847434881,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.0,0.0
2,6,50,1.0,845553381,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.0,0.0
3,7,50,4.5,1106635993,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.0,0.0
4,8,50,5.0,839463644,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333333,0.0,0.000000,0.000000,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9687,610,110746,4.0,1493850133,Hatchet III (2013),0.0,0.0,0.0,0.0,0.500000,0.000000,0.0,0.000000,0.0,0.0,0.500000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0
9688,610,113159,3.5,1493848692,Life After Beth (2014),0.0,0.0,0.0,0.0,0.333333,0.000000,0.0,0.000000,0.0,0.0,0.333333,0.0,0.0,0.000000,0.0,0.333333,0.000000,0.000000,0.0,0.0
9689,610,114707,3.0,1493848404,Horns (2014),0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.500000,0.0,0.0,0.500000,0.0,0.000000,0.000000,0.000000,0.0,0.0
9690,610,130840,4.5,1493848621,Spring (2015),0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.333333,0.0,0.0,0.000000,0.0,0.333333,0.333333,0.000000,0.0,0.0
9691,610,149011,3.5,1493848843,He Never Died (2015),0.0,0.0,0.0,0.0,0.333333,0.000000,0.0,0.333333,0.0,0.0,0.333333,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'film_noir', 'horror', 'imax', 'musical', 'mystery', 'no_genres_listed', 'romance', 'sci_fi', 'thriller', 'war', 'western']

,user_id,item_id,rating,timestamp,title,genres,comedy,crime,drama,horror,test_category
0,1,50,5.0,964982931,"Usual Suspects, The (1995)","[crime, mystery, thriller]",0.000000,1.0,0.000000,0.000000,0.0
1,5,50,4.0,847434881,"Usual Suspects, The (1995)","[crime, mystery, thriller]",0.000000,1.0,0.000000,0.000000,0.0
2,6,50,1.0,845553381,"Usual Suspects, The (1995)","[crime, mystery, thriller]",0.000000,1.0,0.000000,0.000000,0.0
3,7,50,4.5,1106635993,"Usual Suspects, The (1995)","[crime, mystery, thriller]",0.000000,1.0,0.000000,0.000000,0.0
4,8,50,5.0,839463644,"Usual Suspects, The (1995)","[crime, mystery, thriller]",0.000000,1.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...
9687,610,110746,4.0,1493850133,Hatchet III (2013),"[comedy, horror]",0.500000,0.0,0.000000,0.500000,0.0
9688,610,113159,3.5,1493848692,Life After Beth (2014),"[comedy, horror, romance]",0.500000,0.0,0.000000,0.500000,0.0
9689,610,114707,3.0,1493848404,Horns (2014),"[horror, mystery]",0.000000,0.0,0.000000,1.000000,0.0
9690,610,130840,4.5,1493848621,Spring (2015),"[horror, romance, sci_fi]",0.000000,0.0,0.000000,1.000000,0.0
9691,610,149011,3.5,1493848843,He Never Died (2015),"[comedy, drama, horror]",0.333333,0.0,0.333333,0.333333,0.0

['comedy', 'crime', 'drama', 'horror', 'test_category']

In [ ]:
from sklearn.linear_model import LinearRegression

class LinearRegressionRecommender(Recommender):
    """
    Base recommender class.
    """
    
    def __init__(self):
        """
        Initialize base recommender params and variables.
        """
        self.model = None
        self.users_dict = None
        self.user_features = None
        self.item_features = None
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        
        # Transform genres to a more code-friendly form
        
        interactions_df = pd.merge(interactions_df, items_df, on='item_id')
        interactions_df = self._transform_genres(interactions_df)
        
        # Prepare user features

        users_df = calculate_user_genres(interactions_df)
        
        self.users_dict = users_df.to_dict('index')
        
        self.user_features = users_df.columns.tolist()
        
        interactions_df = interactions_df.merge(users_df, on='user_id')
                
        # Prepare item features
        
        interactions_df, self.item_features = calculate_item_genres(interactions_df)

        # Prepare input data and fit the model
    
        interactions_df[self.user_features] = interactions_df[self.user_features] \
            * interactions_df[self.user_features].values
        
        x = interactions_df.loc[:, self.user_features].values
        y = interactions_df['rating'].values
    
        self.model = LinearRegression().fit(x, y)
    
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        # Transform the item to be scored into proper features
        
        items_df = items_df.copy()
        items_df = self._transform_genres(items_df)
        
        items_df, _ = calculate_item_genres(items_df, self.item_features)

        # Score the item
    
        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        for ix, user in users_df.iterrows():
            if user['user_id'] in self.users_dict:
                user_df = pd.DataFrame.from_dict({user['user_id']: self.users_dict[user['user_id']]}, orient='index')
            else:
                user_df = pd.DataFrame.from_dict(
                    {user['user_id']: [1 / len(self.user_features)]*len(self.user_features)}, orient='index')
#             display(user_df)
#             display(items_df)
            input_df = items_df.copy()
            input_df[self.item_features] = items_df[self.item_features] * user_df.values
#             display(input_df)
            scores = self.model.predict(input_df.loc[:, self.item_features].values)
    
            chosen_pos = np.argsort(-scores)[:n_recommendations]
        
            user_recommendations = []
            for item_pos in chosen_pos:
                user_recommendations.append(
                    {
                        'user_id': user['user_id'],
                        'item_id': input_df.iloc[item_pos]['item_id'],
                        'score': scores[item_pos]
                    }
                )
                
            user_recommendations = pd.DataFrame(user_recommendations)

            recommendations = pd.concat([recommendations, user_recommendations])

        return recommendations
    
    def _transform_genres(self, df):
        """
        Transforms a string with genres into a list of cleaned genre names.
        
        :param pd.DataFrame df: A DataFrame with 'genres' column.
        """
        df.loc[:, 'genres'] = df['genres'].str.replace("-", "_", regex=False)
        df.loc[:, 'genres'] = df['genres'].str.replace(" ", "_", regex=False)
        df.loc[:, 'genres'] = df['genres'].str.replace("(", "", regex=False)
        df.loc[:, 'genres'] = df['genres'].str.replace(")", "", regex=False)
        df.loc[:, 'genres'] = df['genres'].str.lower()
        df.loc[:, 'genres'] = df['genres'].str.split("|")
        return df

In [ ]:
# Quick test of the recommender

lr_recommender = LinearRegressionRecommender()
lr_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = lr_recommender.recommend(pd.DataFrame([[1], [2]], columns=['user_id']), ml_movies_df, 10)

recommendations = pd.merge(recommendations, ml_movies_df, on='item_id', how='left')
display(recommendations)

### Train-test split test

In [ ]:
lr_recommender = LinearRegressionRecommender()

t0 = time.time()

results = [['LinearRegressionRecommender'] + list(evaluate_train_test_split_explicit(
    lr_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id', 'rating']], ml_movies_df, seed=seed))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'RMSE', 'MRE', 'TRE'])

display(results)

print('Total evaluation time: {}'.format(time.time() - t0))

### Leave-one-out test

In [ ]:
lr_recommender = LinearRegressionRecommender()

t0 = time.time()

results = [['LinearRegressionRecommender'] + list(evaluate_leave_one_out_explicit(
    lr_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id', 'rating']], ml_movies_df, seed=seed))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'RMSE', 'MRE', 'TRE'])

display(results)

print('Total evaluation time: {}'.format(time.time() - t0))

# TF-IDF Recommender
TF-IDF stands for term frequency–inverse document frequency. Typically Tf-IDF method is used to assign keywords (words describing the gist of a document) to documents in a corpus of documents.

In our case we will treat users as documents and genres as words.

Term-frequency is given by the following formula:
<center>
$$
    \text{tf}(g, u) = f_{g, u}
$$
</center>
where $f_{g, i}$ is the number of times genre $g$ appear for movies watched by user $u$.

Inverse document frequency is defined as follows:
<center>
$$
    \text{idf}(g) = \log \frac{N}{n_g}
$$
</center>
where $N$ is the number of users and $n_g$ is the number of users with $g$ in their genres list.

Finally, tf-idf is defined as follows:
<center>
$$
    \text{tfidf}(g, u) = \text{tf}(g, u) \cdot \text{idf}(g)
$$
</center>

In our case we will measure how often a given genre appears for movies watched by a given user vs how often it appears for all users. To obtain a movie score we will take the average of its genres' scores for this user.

**Task 5.** Implement the following method for calculating a TF-IDF scores in a form of a dict (use defaultdict):

`{(1, 'action'): 0.45306430692185395, (1, 'adventure'): 0.39370003643934415, (1, 'animation'): 0.20886242957049514, ...}`

without using TfidfVectorizer (you can use loops).

Evaluate the TFIDFRecommender with it using leave-one-out procedure for implicit feedback, print HR@1, HR@3, HR@5, HR@10, NDCG@1, NDCG@3, NDCG@5, NDCG@10.

In [ ]:
def calculate_tf_idf_scores():
    # Write your code here
    
    return tfidf_scores

In [ ]:
# Test the method
interactions_df = pd.merge(ml_ratings_df, ml_movies_df, on='item_id')
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace("-", "_", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace(" ", "_", regex=False)
interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.lower()
        
tfidf_scores = calculate_tf_idf_scores(interactions_df)
print(tfidf_scores)

In [ ]:
class TFIDFRecommender(Recommender):
    """
    Recommender based on the TF-IDF method.
    """
    
    def __init__(self):
        """
        Initialize base recommender params and variables.
        """
        self.tfidf_scores = None
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        
        self.tfidf_scores = defaultdict(lambda: 0.0)

        # Prepare the corpus for tfidf calculation
        
        interactions_df = pd.merge(interactions_df, items_df, on='item_id')
        interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace("-", "_", regex=False)
        interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.replace(" ", "_", regex=False)
        interactions_df.loc[:, 'genres'] = interactions_df['genres'].str.lower()
                
        self.tfidf_scores = calculate_tf_idf_scores(interactions_df)
    
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        # Transform genres to a unified form used by the vectorizer
        
        items_df = items_df.copy()
        items_df.loc[:, 'genres'] = items_df['genres'].str.replace("-", "_", regex=False)
        items_df.loc[:, 'genres'] = items_df['genres'].str.replace(" ", "_", regex=False)
        items_df.loc[:, 'genres'] = items_df['genres'].str.lower()
        items_df.loc[:, 'genres'] = items_df['genres'].str.split("|")
                
        # Score items    
        
        for uix, user in users_df.iterrows():
            items = []
            for iix, item in items_df.iterrows():
                score = 0.0
                for genre in item['genres']:
                    score += self.tfidf_scores[(user['user_id'], genre)]
                score /= len(item['genres'])
                items.append((item['item_id'], score))
                
            items = sorted(items, key=lambda x: x[1], reverse=True)
            user_recommendations = pd.DataFrame({'user_id': user['user_id'],
                                                 'item_id': [item[0] for item in items][:n_recommendations],
                                                 'score': [item[1] for item in items][:n_recommendations]})

            recommendations = pd.concat([recommendations, user_recommendations])

        return recommendations

In [ ]:
# Print movies watched by user 1, 2

active_user_movies = ml_df.loc[(ml_df['user_id'] == 1) | (ml_df['user_id'] == 2)]
print("Active users history")
display(active_user_movies)

In [ ]:
# Quick test of the recommender

tfidf_recommender = TFIDFRecommender()
tfidf_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = tfidf_recommender.recommend(pd.DataFrame([[1], [2]], columns=['user_id']), ml_movies_df, 10)

recommendations = pd.merge(recommendations, ml_movies_df, on='item_id', how='left')
print("Recommendations")
display(recommendations)

### Train-test split test

In [ ]:
tfidf_recommender = TFIDFRecommender()

t0 = time.time()

results = [['TFIDFRecommender'] + list(evaluate_train_test_split_implicit(
    tfidf_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id']], ml_movies_df))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(results)

print('Total evaluation time: {}'.format(time.time() - t0))

### Leave-one-out test

In [ ]:
tfidf_recommender = TFIDFRecommender()

t0 = time.time()

results = [['TFIDFRecommender'] + list(evaluate_leave_one_out_implicit(
    tfidf_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id']], ml_movies_df, max_evals=300, seed=6789))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(results)

print('Total evaluation time: {}'.format(time.time() - t0))

**Task 6\*.** Implement an SVRRecommender by replacing the LinearRegression model with the SVR model (`from sklearn.svm import SVR`).

Tune the C and epsilon params of the SVR model to obtain as good results as you can. 

To do tuning properly:

- divide the set into training, validation and test sets (randomly divide the dataset in proportions 60%-20%-20%),
- train the model with different sets of tunable parameters on the training set, 
- choose the best tunable params based on results on the validation set, 
- provide the final evaluation metrics on the test set for the best model obtained during tuning.

Recommended method of tuning: use hyperopt. Install the package using the following command: `pip install hyperopt`
    
Print the RMSE, MAPE and TRE on the test set. Use seed 6789.

In [ ]:
from sklearn.svm import SVR
from sklearn.preprocessing import MultiLabelBinarizer

class SVRRecommender(Recommender):
    """
    SVR recommender class.
    """
    
    def __init__(self, kernel='rbf', C=1.0, epsilon=0.1):
        """
        Initialize base recommender params and variables.
        """
        self.model = None
        self.kernel = kernel
        self.C = C
        self.epsilon = epsilon
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        
        # Write your code here
    
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        # Write your code here

        return recommendations
    
    
# Quick test of the recommender

svr_recommender = SVRRecommender()
svr_recommender.fit(ml_ratings_df, None, ml_movies_df)
recommendations = svr_recommender.recommend(pd.DataFrame([[1], [2], [6]], columns=['user_id']), ml_movies_df, 10)

recommendations = pd.merge(recommendations, ml_movies_df, on='item_id', how='left')
print("Recommendations")
display(recommendations)

### Manually test different param configurations

In [ ]:
svr_recommender = SVRRecommender(kernel='rbf', C=1.0, epsilon=0.1)

results = [['SVRRecommender'] + list(evaluate_train_test_split_explicit(
    svr_recommender, ml_ratings_df.loc[:, ['user_id', 'item_id', 'rating']], ml_movies_df, seed=seed))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'RMSE', 'MRE', 'TRE'])

display(results)

### Tune the SVRRecommender

In [ ]:
from hyperopt import hp, fmin, tpe, Trials

# Split into train_validation and test sets

shuffle = np.arange(len(ml_ratings_df))
rng.shuffle(shuffle)
shuffle = list(shuffle)

train_test_split = 0.8
split_index = int(len(ml_ratings_df) * train_test_split)

train_validation = ml_ratings_df.iloc[shuffle[:split_index]].loc[:, ['user_id', 'item_id', 'rating']]
test = ml_ratings_df.iloc[shuffle[split_index:]].loc[:, ['user_id', 'item_id', 'rating']]

# Tune

def loss(tuned_params):
    svr_recommender = SVRRecommender(kernel='rbf', C=tuned_params['C'], epsilon=tuned_params['epsilon'])
    rmse, mre, tre = evaluate_train_test_split_explicit(
        svr_recommender, train_validation, ml_movies_df, seed=seed)
    return rmse

########################################################################
# Write your code here 
# Read the code above and below and make sure you understand it
# Minimize the above loss function using hyperopt
# Save your best params under best_param_set
########################################################################

# Best params

print("C = {}".format(best_param_set['C']))
print("epsilon = {}".format(best_param_set['epsilon']))
    
# Test

svr_recommender = SVRRecommender(C=best_param_set['C'], epsilon=best_param_set['epsilon'])

results = [['SVRRecommender'] + list(evaluate_train_test_split_explicit(
    svr_recommender, {'train': train_validation, 'test': test}, ml_movies_df, seed=seed))]

results = pd.DataFrame(results, 
                       columns=['Recommender', 'RMSE', 'MRE', 'TRE'])

display(results)

**Task 7.** Gather the results for LinearRegressionRecommender, SVRRecommender, TFIDFRecommender, MostPopularRecommender, HighestRatedRecommender, RandomRecommender from the evaluate_train_test_split_implicit method and print them as a single DataFrame.

In [ ]:
linear_recommender = LinearRegressionRecommender()
svr_recommender = SVRRecommender()
tfidf_recommender = TFIDFRecommender()
most_popular_recommender = MostPopularRecommender()
highest_rated_recommender = HighestRatedRecommender()
random_recommender = RandomRecommender()

recommenders = [linear_recommender, svr_recommender, tfidf_recommender, most_popular_recommender, 
                highest_rated_recommender, random_recommender]

results = []

for recommender in recommenders:
    tmp_result = [[type(recommender).__name__] + list(evaluate_train_test_split_implicit(recommender, ml_ratings_df, ml_movies_df))]

    tmp_result = pd.DataFrame(tmp_result, 
                           columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])
    results.append(tmp_result)

print(pd.concat(results).reset_index(drop=True))    # to reset indexing